### ISSUE TITLE
Wrong Youtube ID saved

### ISSUE THREAD

**Issue by lyssdod** [mirrorfm/mirror.fm#3]
Hi,

Upon examining your code and after looking at 2trancentral export I've noticed that you're saving Youtube's _Activity ID_ instead of actual unique video ID: 

https://github.com/mirrorfm/mirror.fm/blob/master/functions/from-youtube/main.py#L216
https://developers.google.com/youtube/v3/docs/activities#resource

Saving `contentDetails.upload.videoId` would allow direct matching with video IDs from existing Youtube playlists.

**Comment by stephanebruckert** [comment]
Hey @lyssdod, thanks for having a look and reporting this.

Very nice catch, definitely IDs looked wrong. We had both `playlistItem` and `activity` IDs instead of only `videoId`. It is fixed now, so new data will be correct. 

However the old data in the DB is still wrong, which is something to eventually fix depending on whether it is preventing us to do more things or not, I believe
